routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Welcome
Route::get('/', function()
{
	return view('welcome');
});
Route::get('/articles', function()
{
	return view('welcome');
});

// Testing
Route::get('/test', function () {
    return view('auth.userRegister');
});
Route::get('/articlevue','articlesController@vue');
Route::get('/articlevuewelcome','articlesController@vuewelcome');
Route::get('/articlevueread/{id}','articlesController@vuereadmore');

// Login
Route::match(['get', 'post'], '/loginPage', 'loginAppController@login')->name('loginPage');

// Register
Route::match(['get', 'post'], '/registerPage', 'registerAppController@register')->name('registerPage');

// User Dashboard
Route::group(['prefix' => 'user', 'middleware' => ['web', 'ednoAuth:itsUser']], function() {
    Route::get('/dashboard', 'userAppController@dashboard');
    Route::resource('/articles','articlesController');
    Route::get('/readmore/{title}','articlesController@readmore');
    Route::get('/logout', 'userAppController@logout');
    Route::get('/{id}/profile', 'userAppController@profile');
    Route::post('/profile/edit', 'userAppController@profileEdit');

});

// Default Laravel
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class article extends Model
{
    protected $filable =['id','title','articles'];

    public function User()
    {
    	return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/articlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\article;
use Auth;
use Session;
use DB;


class articlesController extends Controller
{
    public function index()
    {
    	$user_id = Auth::User()->id;

    	$articles  = article::where('user_id', $user_id)->orderBy('id','asc')->paginate(6);


    	return view('articles.data-article',compact('articles'));

    }
    public function create(){
    	return view('articles.create-articles');
    }
    public function store(Request $request){
        $this->validate($request,array(
            'title'=> 'required|unique:articles'
        ));
        $id = Auth::user()->id;

        $store = new article;
        $store -> user_id  = $id;
        $store -> title    = $request -> title;
        $store -> articles = $request -> articles;

        $store-> save();
        $title = str_replace(' ', '-', $store->title);

        $back = redirect('/user/readmore/'.$title);


        return $back;

    }
    // public function show($title){
    // 	$articles = article::where('title',$title)->get();

    // 	return view('articles.single-article',compact('articles'));

    // }
    public function readmore($title){
        $titles = str_replace('-', ' ', $title);

        $articles = article::where('title',$titles)->first();
        return view('articles.single-article',compact('articles'));
    }
    public function edit($id){
        $articles = article::find($id);
        return view('articles.update-article',compact('articles'));
    }
    public function update(Request $request,$id)
    {

        $user_id = Auth::User()->id;

        $update= article::find($id);

        $title = $request->input('title');
        $unique = article::where('title', $title)->first();
        if ($unique !== null) {
            if ($unique->id === $update->id) {
                $update -> title = $title;
            }
            else {
                Session::flash('notif', 'tulis judul artikel baru karena yang ini sudah digunakan');
                return redirect()->back();
            }
        } else {
            $update -> title = $title;
        }

        // $update-> title = $request -> title;
        $update -> articles = $request -> articles;
        $update ->save();
        $title = str_replace(' ', '-', $update->title);

        $back = redirect('/user/readmore/'.$title);


        return $back;

    }
    public function destroy($id){
        $article = article::find($id);
        $article->delete();

        $back = redirect()->route('articles.index');

        return $back;


    }
    public function vue(){
        $articles=article::all();
        return $articles;
    }
    public function vuewelcome(){
         $articles = article::orderBy("id", "DESC")->paginate(3);
        return response()->json($articles);
    }
    public function vuereadmore($id) {
        $title=str_replace('-', ' ', $id);
        $read = article::where('title',$title)->first();
        $user_id = $read -> user_id;
        $user = User::findOrFail($user_id);
        $userImage = str_replace('public', 'storage', $user->image);


        return response()->json([
            'read' => $read,
            'user' => $user,
            'image' => $userImage
        ], 200);
    }
}

resources/views/articles/create-articles.blade.php
@extends('layouts.user.user-master')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <a href="../../user/articles"><button class="btn btn-simple" id="icon2"><i class="fa fa-arrow-circle-left"></i> <span id="spanIcon"> Kembali</span></button>
                    </a>
                </div>
                <div class="col-md-8 offset-md-1">  
                    <h3 class="card-title">Buat Artikel Baru Anda</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form  action="{{ route('articles.store') }}" method="post" aria-label="{{ _('articles') }}">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="title">Judul</label>
                    <input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" data-validation-length="min30" aria-describedby="title"  placeholder="Tulis judul artikel anda" required="required">
                    @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group " >
                    <label for="article">Tulis Artikel</label>
                    <textarea name="articles" class="form-control" id="summernote"></textarea>
                </div>
                <div class="tools pull-right" id="icon">
                    <button type="submit" class="btn btn-outline-primary rounded-circle ">
                        <i class="fa fa-send"></i>
                    </button>
                    <button type="reset" class="btn btn-outline-danger rounded-circle ">
                        <i class="fa fa-undo"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/articles/data-article.blade.php
@extends('layouts.user.user-master')
@section('content')
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12 pull-right">
				<a href="{{ route('articles.create') }}"><button class="btn btn-outline-primary pull-right"><i class="fa fa-plus"></i>tulis artikel</button></a>

			</div>
		</div>
		<div class="row mt-4">
			@if(count($articles) > 0)
			@foreach($articles as $article)
			<div class="col-md-4">
				<div class="card" id="card">
					<div class="header text-center bg-light">
						<h3 class="title-article p-3">{{ $article -> title }}</h3>
					</div>
					<div class="card-body text-center mb-2" id="article" >
						{!!$article-> articles!!}
					</div>
					<a href=" readmore/{{ str_replace(' ', '-', $article->title), Request::session()->put('id', $article->id)}}" class="text-center mt-2"><i class="fa fa-arrow-circle-right"></i>read more...</a>
					<hr>
					<div class="footer">
						<div class="row">
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-6">
										<img src="{{ Storage::url(Auth::user()->image) }}" alt="..." class="border-gray pull-left pl-2" style="height: 
										50px;width: 100%;">
									</div>
									<div class="col-md-6 pull-left">
										<p class="small ml-1 ">{{ Auth::user()->name }}
											<small style="opacity: 0.8;">{{ date('d-m-Y', strtotime($article -> created_at)) }}</small>
										</p>
									</div>
								</div>
							</div>
							<div class="col-md-5">
								<div class="row pull-right">
									<a href="/user/articles/{{ $article -> id }}/edit"><button class="btn btn-outline-info rounded-circle mr-2" ><i class="fa fa-pencil" style="font-size: 20px;"></i></button></a>
									<form id="hapusData" action="{{ route('articles.destroy',['id'=>$article->id]) }}" method="post">
										{{ csrf_field() }}
										<button type="submit" class="btn btn-outline-danger rounded-circle" onclick="return confirm('are you sure?')" data-id="{{ $article->id }}"><i class="fa fa-trash" style="font-size:20px; "></i></button>
										<input type="hidden" name="_method" value="delete">
									</form>
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			@endforeach
			@else
			<div class="col-md-12 text-center">
				<h2>Klik tombol tulis artikel untuk menulis artikel baru</h2>
			</div>
			@endif
		</div>
		<div class="row">
			<div class="col-md-12">
				<ul class="pull-right">{{ $articles->links() }}</ul>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/articles/single-article.blade.php
@extends('layouts.user.user-master')
<style>

</style>
@section('content')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9" style="border-radius: 5px;">
				<div class="card">
					<div class="header bg-light pt-3" id="title">
						<div class="row">
							<div class="col-md-2">
								<a href="../articles" class="btn btn-simple" id="icon2"><i class="fa fa-arrow-circle-left"></i><span id="spanIcon" style="font-size: 20px;">  Kembali</span></a>
							</div>
							<div class="col-md-10 text-center pull-left">
								<h3 class="title-article ">{{ $articles ->title }}</h3>
							</div>	
						</div>
					</div>
					<div class="card-body text-center">
						{!!$articles-> articles !!}
					</div>
					<hr>
					<div class="footer mr-2 pr-2">
						<div class="row">
							<div class="col-md-4">
								<img src="{{ Storage::url(Auth::user()->image) }}" alt="..." class="avatar border-gray pull-left pl-2"  style="height: 
								50px;width: 25%;">
								<p class="small pull-left ml-1">{{ Auth::user()->name }} <br>{{ date('y-m-d',strtotime($articles->created_at)) }}</p>
							</div>
							<div class="col-sm-8" id="icon2">
								<div class="row pull-right pr-2">
									<a href="../articles/{{ $articles->id }}/edit"><button class="btn btn-outline-info rounded-circle mr-2 pull-right"><i class="fa fa-pencil "></i></button></a>
									<form id="hapusData" action="{{ route('articles.destroy',['id'=>$articles->id]) }}" method="post">
										<button type="submit" onclick="return confirm('are you sure?')" class="btn btn-outline-danger rounded-circle pull-right "><i class="fa fa-trash"></i></button>
										{{ csrf_field() }}
										<input type="hidden" name="_method" value="delete">
									</form>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card card-user">
					<div class="image">
						<img src="{{ Storage::url(Auth::user()->image) }}"/ style="height: 150px; width: 100%;">
					</div>
					<div class="content">
						<div class="author">
							<a href="#">
								<img class="avatar border-gray" src="{{ Storage::url(Auth::user()->image) }}" alt="..."/>
								<h4 class="title">{{ Auth::user()->name }}<br />
									
								</h4>
							</a>
						</div>
						<p class="description text-center">"{{ Auth::user()->about }}"
						</p>
					</div>
					{{-- <hr>
					<div class="text-center">
						<button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
						<button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
						<button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>
					</div> --}}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/articles/update-article.blade.php
@extends('layouts.user.user-master')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <a href="{{ URL::previous() }}" class="btn btn-simple" id="icon2"><i class="fa fa-arrow-circle-left"></i><span id="spanIcon" style="font-size: 20px;">  Kembali</span></a>
                </div>
                <div class="col-md-8 offset-md-1">
                    <h3 class="card-title">Halaman Edit Artikel </h3> 
                </div>
            </div>
        </div>
    </div>
    @if(Session::has('notif'))
        <div class="sufee-alert alert with-close alert-info alert-dismissible fade show mt-2 ml-3" id="close">
            <strong>Notif: </strong>
            {!! session('notif') !!}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
   @endif
  <div class="row mt-3">
    <div class="col-md-12">
        <form action="{{ route('articles.update',['id'=>$articles->id]) }}" method="post">
            {{ method_field('patch') }}
            {{ csrf_field() }}
            <div class="form-group">
                <label for="title">Judul</label>
                <input type="text" class="form-control" length="200" name="title" aria-describedby="title" placeholder="tulis judul artikel anda" value="{{ $articles -> title }}">
            </div>
            <div class="form-group ">
                <label for="article"><ARTICLE>Tulis Artikel Anda</ARTICLE></label>
                <textarea name="articles" class="form-control" id="summernote">{{ $articles-> articles }}</textarea>
            </div>
            <div class="tools pull-right" id="icon">
                <button type="submit" class="btn btn-outline-primary rounded-circle ">
                    <i class="fa fa-send" ></i>
                </button>
                <button type="button" class="btn btn-outline-danger rounded-circle " onclick="clearForm(this.form)">
                    <i class="fa fa-undo"></i>
                </button>
            </div>
        </form>
    </div>
</div>
</div>
<script>
    function clearForm(oForm) {

        var elements = oForm.elements; 

        oForm.reset();

        for(i=0; i<elements.length; i++) {

            field_type = elements[i].type.toLowerCase();


            switch(field_type) {

                case "text":                                           
                elements[i].value = ""; 
                ;
                break;

                default: 
                break;
            }
        }
    }

</script>
@endsection